# Generated by Django 5.2.1 on 2025-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=125)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
    ]
