# Generated by Django 5.2.1 on 2025-06-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='film',
            table='films',
        ),
    ]
