# Generated by Django 5.2.1 on 2025-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(related_name='films', to='films.tag'),
        ),
    ]
