# Generated by Django 5.2.1 on 2025-06-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_shelfentry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shelfentry',
            table='shelf_entries',
        ),
    ]
