# Generated by Django 5.2.1 on 2025-06-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_created_at_film_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.tag'),
        ),
    ]
