# Generated by Django 5.2.1 on 2025-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_remove_film_genre_remove_film_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
