# Generated by Django 5.2.1 on 2025-06-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_moviefolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefolder',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folder', to='films.film'),
        ),
    ]
