# Generated by Django 5.2.1 on 2025-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_moviefolder_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
