# Generated by Django 5.2.1 on 2025-06-18 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_alter_film_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moviefolder',
            index=models.Index(fields=['user', 'status'], name='ix_films_user_id_status'),
        ),
    ]
