# Generated by Django 5.2.1 on 2025-06-19 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_moviefolder_ix_films_user_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefolder',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
